### ISSUE TITLE
Repacking lens 

### ISSUE THREAD

**Issue by vintendpower** [ptrumpis/snap-lens-tool#11]
Wanted to say awesome work first off. 

I was able to extract the files from a lens and change a few jpegs in them.. I repacked the lens.. now i have a ins file.. how Would I go about using this now modded and repacked lens in Snapcamera ?

**Comment by ptrumpis** [comment]
Another user created this video today:
https://www.youtube.com/watch?v=Pp6ljLzRjnU

It covers the process of importing modded lenses.

Uploading modified lenses will become easier with the upcoming server release.
Right now, it's not very user friendly.
